### ISSUE TITLE
SCL3711 reader disappears from USB bus after running LLCP example

### ISSUE THREAD

**Issue by nehpetsde** [nfcpy/nfcpy#15]
After running an LLCP example the reader disappears form the USB bus. Running the same example again produces the error:

$ ./llcp-test-client.py --quirks android -t 9
searching for a usb tty reader
searching for a usb bus reader
Traceback (most recent call last):
  File "./llcp-test-client.py", line 658, in <module>
    main()
  File "./llcp-test-client.py", line 541, in main
    clf = nfc.ContactlessFrontend(options.device)
  File "/Users/andre/work/nfcpy/nfc/clf.py", line 50, in __init__
    raise LookupError("couldn't find any usable nfc reader")
LookupError: couldn't find any usable nfc reader

I then have to remove and insert the USB reader to have it detected.

**Comment by nehpetsde** [comment]
(by stephen-tiedemann)
Still waiting for an SCL 3711 reader to verify the problem.

**Comment by nehpetsde** [comment]
(by stephen-tiedemann)
Tested with an SCL3711 on Linux it should work since trunk revision 67

**Comment by nehpetsde** [comment]
(by andrefcruz)
I still encounter the problem:

2011-06-14 16:11:52,306 - nfc.dev.pn53x - INFO - 20962 - pn53x.py:47 - searching for a usb tty reader
2011-06-14 16:11:52,310 - nfc.dev.pn53x - INFO - 20962 - pn53x.py:54 - searching for a usb bus reader
2011-06-14 16:11:52,335 - nfc.dev.pn53x - INFO - 20962 - pn53x.py:59 - trying reader at usb port 002:056
2011-06-14 16:11:52,337 - nfc.dev.pn53x - DEBUG - 20962 - pn53x.py:200 - write 0 byte
2011-06-14 16:11:53,311 - nfc.dev.pn53x - DEBUG - 20962 - pn53x.py:200 - write 0 byte
Exception usb.USBError: 'No error' in <bound method pn53x_usb.__del__ of <nfc.dev.pn53x.pn53x_usb object at 0x8b55bcc>> ignored
Traceback (most recent call last):
  File "./vm.py", line 262, in <module>
    start_trocos()
  File "./vm.py", line 204, in start_trocos
    clf = nfc.ContactlessFrontend()
  File "/mnt/hgfs/code/vmachine/nfcpy/nfc/clf.py", line 50, in __init__
    raise LookupError("couldn't find any usable nfc reader")
LookupError: couldn't find any usable nfc reader

**Comment by nehpetsde** [comment]
(by stephen-tiedemann)
Andre, are you running on Linux or Ubuntu?

**Comment by nehpetsde** [comment]
(by andrefcruz)
Debian stable (6.0) running as a guest operating system on a vmware fusion/OSX host. On the OSX host I cannot reproduce this behavior. I'm going to try this using Virtualbox or a real Debian box if I can get my hands on one.

Here is another run:

root@cobaia:/mnt/hgfs/code/vmachine/nfcpy/examples# ./llcp-test-client.py --quirks android -t 9
searching for a usb tty reader
searching for a usb bus reader
trying reader at usb port 002:011
chipset is a PN533 version 2.7
ATR_RES(nfcid3=fcc9b7f7949800843e28, did=00, bs=00, br=00, to=0e, pp=32, gb=46666d01011003020001040196)
running on Initiator
recv-lto: 1500
recv-miu: 1024
recv-wks: 3
send-agf: False
send-lsc: 3
send-lto: 1000
send-miu: 128
send-wks: 1
Test 9: service name lookup
shutdown on link disruption
FAIL: no answer for 'urn:nfc:sn:sdp' lookup
I was the Initiator
root@cobaia:/mnt/hgfs/code/vmachine/nfcpy/examples# ./llcp-test-client.py --quirks android -t 9
searching for a usb tty reader
searching for a usb bus reader
trying reader at usb port 002:011
Exception usb.USBError: 'No error' in <bound method pn53x_usb.__del__ of <nfc.dev.pn53x.pn53x_usb object at 0x86ba38c>> ignored
Traceback (most recent call last):
  File "./llcp-test-client.py", line 658, in <module>
    main()
  File "./llcp-test-client.py", line 541, in main
    clf = nfc.ContactlessFrontend(options.device)
  File "/mnt/hgfs/code/vmachine/nfcpy/nfc/clf.py", line 50, in __init__
    raise LookupError("couldn't find any usable nfc reader")
LookupError: couldn't find any usable nfc reader

**Comment by nehpetsde** [comment]
(by andrefcruz)
I tried this on Debian/VirtualBox/OSX and also could not reproduce this behavior. So it seems it's related to VMWare.

Sorry about that. :)

**Comment by nehpetsde** [comment]
(by andrefcruz)
Now this is where it gets weird. I was having no problems until I connected my bluetooth adapter to the USB bus. Then the usual errors pop up:


2011-06-15 14:20:07,411 - find_peer - DEBUG - 1361 - vm.py:192 - No peer from listen
2011-06-15 14:20:07,412 - nfc.dev.pn53x - DEBUG - 1361 - pn53x.py:335 - polling for a dep target
2011-06-15 14:20:07,412 - nfc.dev.pn53x - DEBUG - 1361 - pn53x.py:200 - write 40 byte
  0000: d4 56 01 02 07 00 ff ff 00 03 01 fe 94 37 a0 77 .V...........7.w
  0010: 8a f6 74 02 46 66 6d 01 01 10 02 02 03 80 03 02 ..t.Ffm.........
  0020: 00 03 04 01 64 07 01 03                         ....d...
2011-06-15 14:20:07,964 - nfc.dev.pn53x - DEBUG - 1361 - pn53x.py:353 - polling for a type 3 tag
2011-06-15 14:20:07,964 - nfc.dev.pn53x - DEBUG - 1361 - pn53x.py:200 - write 9 byte
  0000: d4 4a 01 02 00 ff ff 01 03                      .J.......
2011-06-15 14:20:08,011 - nfc.dev.pn53x - DEBUG - 1361 - pn53x.py:220 - read 3 byte
  0000: d5 4b 00                                        .K.
2011-06-15 14:20:08,012 - nfc.dev.pn53x - DEBUG - 1361 - pn53x.py:200 - write 9 byte
  0000: d4 4a 01 01 00 ff ff 01 03                      .J.......
2011-06-15 14:20:08,110 - nfc.dev.pn53x - DEBUG - 1361 - pn53x.py:220 - read 3 byte
  0000: d5 4b 00                                        .K.
2011-06-15 14:20:08,110 - nfc.dev.pn53x - DEBUG - 1361 - pn53x.py:200 - write 4 byte
  0000: d4 32 01 00                                     .2..
2011-06-15 14:20:08,126 - nfc.dev.pn53x - DEBUG - 1361 - pn53x.py:220 - read 2 byte
  0000: d5 33                                           .3
2011-06-15 14:20:08,126 - find_peer - DEBUG - 1361 - vm.py:204 - No peer from poll

…

connected bluetooth dongle

2011-06-15 14:20:08,126 - nfc.dev.pn53x - DEBUG - 1361 - pn53x.py:376 - listen: gb=46666d0101100202038003020003040164070103 timeout=264 ms
2011-06-15 14:20:08,126 - nfc.dev.pn53x - DEBUG - 1361 - pn53x.py:200 - write 59 byte
  0000: d4 8c 02 01 01 00 00 00 40 01 fe 77 e0 28 be 98 ........@..w.(..
  0010: b8 00 00 00 00 00 00 00 00 ff ff 01 fe 77 e0 28 .............w.(
  0020: be 98 b8 00 00 14 46 66 6d 01 01 10 02 02 03 80 ......Ffm.......
  0030: 03 02 00 03 04 01 64 07 01 03 00                ......d....
2011-06-15 14:20:08,404 - nfc.dev.pn53x - DEBUG - 1361 - pn53x.py:200 - write 0 byte
2011-06-15 14:20:08,408 - find_peer - DEBUG - 1361 - vm.py:192 - No peer from listen
2011-06-15 14:20:08,408 - nfc.dev.pn53x - DEBUG - 1361 - pn53x.py:335 - polling for a dep target
2011-06-15 14:20:08,408 - nfc.dev.pn53x - DEBUG - 1361 - pn53x.py:200 - write 40 byte
  0000: d4 56 01 02 07 00 ff ff 00 03 01 fe f6 a8 fd a3 .V..............
  0010: 23 2b 8b a4 46 66 6d 01 01 10 02 02 03 80 03 02 #+..Ffm.........
  0020: 00 03 04 01 64 07 01 03                         ....d...
2011-06-15 14:20:09,568 - nfc.dev.pn53x - DEBUG - 1361 - pn53x.py:353 - polling for a type 3 tag
2011-06-15 14:20:09,568 - nfc.dev.pn53x - DEBUG - 1361 - pn53x.py:200 - write 9 byte
  0000: d4 4a 01 02 00 ff ff 01 03                      .J.......
Traceback (most recent call last):
  File "./vm.py", line 273, in <module>
    start_trocos()
  File "./vm.py", line 232, in start_trocos
    peer = find_peer(clf, general_bytes)
  File "./vm.py", line 194, in find_peer
    peer = clf.poll(general_bytes)
  File "/mnt/code/vmachine/nfcpy/nfc/clf.py", line 74, in poll
    data = self.dev.poll_tt3()
  File "/mnt/code/vmachine/nfcpy/nfc/dev/pn53x.py", line 360, in poll_tt3
    try: rsp = self.dev.in_list_passive_target(1, br, poll_ffff)[0]
  File "/mnt/code/vmachine/nfcpy/nfc/dev/pn53x.py", line 99, in in_list_passive_target
    raise IOError("in_list_passive_target")
IOError: in_list_passive_target
2011-06-15 14:20:09,623 - nfc.dev.pn53x - DEBUG - 1361 - pn53x.py:200 - write 0 byte

How can another usb device influence nfcpy?

**Comment by nehpetsde** [comment]
(by andrefcruz)
Some more info, this looks like some kind of USB bug.

I run the following program:
dh.bulkWrite(usb_out, "\x00\x00\xFF\x00\xFF\x00")                        # ACK
dh.bulkWrite(usb_out, "\x00\x00\xFF\x00\xFF\x00")                        # ACK
dh.bulkWrite(usb_out, "\x00\x00\xFF\x00\xFF\x00")                        # ACK
dh.bulkWrite(usb_out, "\x00\x00\xFF\x00\xFF\x00")                        # ACK
dh.bulkWrite(usb_out, "\x00\x00\xFF\x02\xFE\xD4\x02\x2a\x00")     # get firmware
dh.bulkRead(usb_inp, 256, 100)                                                   # expect ACK
dh.bulkRead(usb_inp, 256, 100)                                                   # read firmware

and this is the usb trace:
d4ee7b40 486055832 S Bo:2:003:4 -115 6 = 0000ff00 ff00
d4ee7b40 486065699 C Bo:2:003:4 0 6 >
d4ee7b40 486067476 S Bo:2:003:4 -115 6 = 0000ff00 ff00
d4ee7b40 486198123 C Bo:2:003:4 -2 0
d4ee7b40 486202289 S Bo:2:003:4 -115 6 = 0000ff00 ff00
d4ee7b40 486224246 C Bo:2:003:4 0 6 >
d4ee7b40 486226456 S Bo:2:003:4 -115 6 = 0000ff00 ff00
d4ee7b40 486327727 C Bo:2:003:4 -2 0
d4ee7b40 486330026 S Bo:2:003:4 -115 9 = 0000ff02 fed4022a 00
d4ee7b40 486361420 C Bo:2:003:4 0 9 >
d4ee7b40 486365289 S Bi:2:003:4 -115 256 <
d4ee7b40 486370308 C Bi:2:003:4 -121 13 = 0000ff06 fad50333 020707e5 00
d4ee7b40 486371293 S Bi:2:003:4 -115 256 <
d4ee7b40 486505033 C Bi:2:003:4 -2 0

So the odd commands succeed and the even ones timeout… Now I run "hciconfig hci0 down" to disable my USB bluetooth dongle:
d4ee71c0 573547640 S Co:2:004:0 s 20 00 0000 0000 0003 3 = 030c00
d612d540 573801964 C Ii:2:004:1 -2:1 0
d612d440 573824740 C Bi:2:004:2 -2 0
d612d4c0 573828417 C Bi:2:004:2 -2 0

And I run my test program again:
d612d4c0 607077220 S Bo:2:003:4 -115 6 = 0000ff00 ff00
d612d4c0 607084977 C Bo:2:003:4 0 6 >
d612d4c0 607085350 S Bo:2:003:4 -115 6 = 0000ff00 ff00
d612d4c0 607088655 C Bo:2:003:4 0 6 >
d612d4c0 607089966 S Bo:2:003:4 -115 6 = 0000ff00 ff00
d612d4c0 607092308 C Bo:2:003:4 0 6 >
d612d4c0 607093644 S Bo:2:003:4 -115 6 = 0000ff00 ff00
d612d4c0 607095641 C Bo:2:003:4 0 6 >
d612d4c0 607096944 S Bo:2:003:4 -115 9 = 0000ff02 fed4022a 00
d612d4c0 607098583 C Bo:2:003:4 0 9 >
d612d4c0 607099712 S Bi:2:003:4 -115 256 <
d4ee71c0 607101750 C Co:2:004:0 0 3 >
d612d4c0 607102836 C Bi:2:003:4 -121 13 = 0000ff06 fad50333 020707e5 00
d612d4c0 607103810 S Bi:2:003:4 -115 256 <
d612d4c0 607238525 C Bi:2:003:4 -2 0

All works now… This seems related to http://code.google.com/p/libnfc/issues/detail?id=114 but in this case it's not just one ACK that gets lost. And I've tried this with Debian unstable (latest kernel) and libusb 1.0… I'm at a loss here. Can this be a USB bug in the linux kernel or a bug in the USB implementation of SCL3711?

**Comment by nehpetsde** [comment]
(by deavonb)
Fellas,

Is there anything that I can do to help with this effort? I've attempted to correct the issue myself, but my python experience level is unfortunately not sufficient to make an accurate assessment. I can perform testing using the SCL3711 device, or can attempt to reverse engineer the issue with some direction.

Thanks!
Deavon

**Comment by nehpetsde** [comment]
(by deavonb)
Please ignore the above comment. I'm simply overly-critical of my python experience, and will likely have sufficient skill in implementing a solution. ;-)

**Comment by nehpetsde** [comment]
(by stephen-tiedemann)
This should be solved by now. Tests done before the recent merge from dev-phdc were all successful.  I will close this bug as fixed.
