### ISSUE TITLE
acr122 driver throws exception on frame length check

### ISSUE THREAD

**Issue by nehpetsde** [nfcpy/nfcpy#18]
# python tagtool.py -d nfc
[main] enable debug output for module 'nfc'
[nfc.clf] searching for reader with path 'usb'
[nfc.dev.transport] using pyusb version 0.x
[nfc.dev.transport] path matches '^(usb|)$'
[nfc.dev] trying usb:072f:2200
[nfc.dev] import nfc.dev.acr122
[nfc.dev.transport] >>> 6f050000000000000000ff00480000
[nfc.dev.transport] <<< 800a000000000002810041435231323255323133
Traceback (most recent call last):
  File "tagtool.py", line 479, in <module>
    TagTool().run()
  File "/home/joggler/nfc/nfcpy/examples/cli.py", line 283, in run
    while self.run_once() and self.options.loop:
  File "/home/joggler/nfc/nfcpy/examples/cli.py", line 230, in run_once
    try: clf = nfc.ContactlessFrontend(device)
  File "/home/joggler/nfc/nfcpy/nfc/clf.py", line 105, in __init__
    if path and not self.open(path):
  File "/home/joggler/nfc/nfcpy/nfc/clf.py", line 156, in open
    self.dev = nfc.dev.connect(path)
  File "/home/joggler/nfc/nfcpy/nfc/dev/__init__.py", line 64, in connect
    device = driver.init(usb)
  File "/home/joggler/nfc/nfcpy/nfc/dev/acr122.py", line 121, in init
    chipset = Chipset(transport)
  File "/home/joggler/nfc/nfcpy/nfc/dev/acr122.py", line 40, in __init__
    reader_version = self.ccid_xfr_block(bytearray.fromhex("FF00480000"))
  File "/home/joggler/nfc/nfcpy/nfc/dev/acr122.py", line 81, in ccid_xfr_block
    if len(frame) != 10 + struct.unpack("<I", frame[1:5])[0]:
struct.error: unpack requires a string argument of length 4

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2014-01-31T15:25:58Z
 * owner: stephen-tiedemann
 * assignee: stephen-tiedemann
 * the launchpad url was https://bugs.launchpad.net/bugs/1274973

**Comment by nehpetsde** [comment]
(by stephen-tiedemann)
This was related to Python version 2.7.3 being used, later versions don't show that behaviour. Best fix is to select bytes 1-4 out of the received frame by using buffer(frame, 1, 4).

**Comment by nehpetsde** [comment]
(by stephen-tiedemann)
Fix released with trunk revision 218

**Comment by nehpetsde** [comment]
(by jeroen-benda)
I recently downloaded nfcpy 0.9 which according to the code page should include up to revision 220. I however still have the same issue as described.

pi@rpi02 ~/nfcpy $ sudo python examples/tagtool.py -d nfc
[main] enable debug output for module 'nfc'
[nfc.clf] searching for reader with path 'usb'
[nfc.dev.transport] using pyusb version 0.x
[nfc.dev.transport] path matches '^(usb|)$'
[nfc.dev] trying usb:072f:2200
[nfc.dev] import nfc.dev.acr122
[nfc.dev.transport] >>> 6f050000000000000000ff00480000
[nfc.dev.transport] <<< 800a000000000000810041435231323255323133
Traceback (most recent call last):
  File "examples/tagtool.py", line 479, in <module>
    TagTool().run()
  File "/home/pi/nfcpy/examples/cli.py", line 283, in run
    while self.run_once() and self.options.loop:
  File "/home/pi/nfcpy/examples/cli.py", line 230, in run_once
    try: clf = nfc.ContactlessFrontend(device)
  File "/home/pi/nfcpy/nfc/clf.py", line 105, in __init__
    if path and not self.open(path):
  File "/home/pi/nfcpy/nfc/clf.py", line 156, in open
    self.dev = nfc.dev.connect(path)
  File "/home/pi/nfcpy/nfc/dev/__init__.py", line 64, in connect
    device = driver.init(usb)
  File "/home/pi/nfcpy/nfc/dev/acr122.py", line 121, in init
    chipset = Chipset(transport)
  File "/home/pi/nfcpy/nfc/dev/acr122.py", line 40, in __init__
    reader_version = self.ccid_xfr_block(bytearray.fromhex("FF00480000"))
  File "/home/pi/nfcpy/nfc/dev/acr122.py", line 81, in ccid_xfr_block
    if len(frame) != 10 + struct.unpack("<I", frame[1:5])[0]:
struct.error: unpack requires a string argument of length 4

My python version and trying the code you showed in
https://bugs.launchpad.net/nfcpy/+bug/1257591

pi@rpi02 ~/nfcpy $ python
Python 2.7.3 (default, Mar 18 2014, 05:13:23)
[GCC 4.6.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import struct
>>> struct.unpack("<I", "\x0A\x00\x00\x00")
(10,)
>>> struct.unpack("<I", bytearray("\x0A\x00\x00\x00"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
struct.error: unpack requires a string argument of length 4
>>>

I would appreciate you helping me to get this resolved.

**Comment by nehpetsde** [comment]
(by stephen-tiedemann)
Definitely fixed with revision 218 by encapsulating the frame[1:5] slice into a buffer().
