### ISSUE TITLE
Cant find path /dev

### ISSUE THREAD

**Issue by PVTPAY** [nfcpy/nfcpy#197]
Hi, 
I’m trying to run nfcpy on Windows 10 64 bit using an Adafruit PN532v1.6. I installed WinUSB over Zadig and libusb according to the installation instructions. When I want to check everything with 
$ python -m nfc --search-tty
I get: 

>This is the 1.0.3 version of nfcpy run in Python 3.9.5
on Windows-10-10.0.19043-SP0
I'm now searching your system for contactless devices
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\svenv\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\nfc\__main__.py", line 214, in <module>
    main(parser.parse_args())
  File "C:\Users\svenv\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\nfc\__main__.py", line 71, in main
    for dev in nfc.clf.transport.TTY.find("tty")[0]:
  File "C:\Users\svenv\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\nfc\clf\transport.py", line 83, in find
    ttys = [fn for fn in os.listdir('/dev') if TTYS.match(fn)]
FileNotFoundError: [WinError 3] Das System kann den angegebenen Pfad nicht finden: '/dev'< 

It says that the system can't find the path "/dev".

Any idea how i could fix that?

Thank you and greetings

**Comment by nehpetsde** [comment]
The `--search-tty` option is only for searching through Linux serial connections. No similar thing is implemented for Windows COM ports and I would be surprised if you're attempting to use a reader with serial interface under Windows - this is mostly used with embedded Linux devices.
