### ISSUE TITLE
``ValueError: Unknown format code 'x' for object of type 'str'``

### ISSUE THREAD

**Issue by JulianOrteil** [nfcpy/nfcpy#207]
The full stacktrace Python is giving me:
```python
Traceback (most recent call last):
  File "[C:\Users\user\.conda\envs\nfcapp\lib\site-packages\nfc\tag\__init__.py]()", line 410, in __init__
    default = "tag command error {errno} (0x{errno:x})".format(errno=errno)
ValueError: Unknown format code 'x' for object of type 'str'
```

This is being caused by ``Type2TagCommandError``. ``errno`` appears to be a string like "invalid page number" and a couple others. It causes my program to silently fail on the backend which raises a variety of issues I really can't account for. I'm currently using multiple ACR122T devices (a variant of the ACR122U).

I can't give an MRE as this error appears to be intermittent unfortunately.

**Comment by JulianOrteil** [comment]
Update:

After catching the error, I got a better stacktrace that might help track down the issue:
```python
Traceback (most recent call last):

  File "c:\Users\user\.vscode\extensions\ms-python.python-2022.0.1814523869\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydev_bundle\pydev_monkey.py", line 1054, in __call__
    ret = self.original_func(*self.args, **self.kwargs)
          │    │              │    │       │    └ {}
          │    │              │    │       └ <_pydev_bundle.pydev_monkey._NewThreadStartupWithTrace object at 0x000001B704BBD220>
          │    │              │    └ ()
          │    │              └ <_pydev_bundle.pydev_monkey._NewThreadStartupWithTrace object at 0x000001B704BBD220>
          │    └ <bound method Thread._bootstrap of <Thread(ThreadPoolExecutor-35_2, started daemon 7560)>> 
          └ <_pydev_bundle.pydev_monkey._NewThreadStartupWithTrace object at 0x000001B704BBD220>

  File "C:\Users\user\.conda\envs\nfcapp\lib\threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x000001B7665313A0>
    └ <Thread(ThreadPoolExecutor-35_2, started daemon 7560)>

  File "C:\Users\user\.conda\envs\nfcapp\lib\threading.py", line 932, in _bootstrap_inner        
    self.run()
    │    └ <function Thread.run at 0x000001B7665310D0>
    └ <Thread(ThreadPoolExecutor-35_2, started daemon 7560)>

  File "C:\Users\user\.conda\envs\nfcapp\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ThreadPoolExecutor-35_2, started daemon 7560)>
    │    │        │    └ (<weakref at 0x000001B704BB7680; to 'ThreadPoolExecutor' at 0x000001B704A3F0A0>, <_queue.SimpleQueue object at 0x000001B704BC...
    │    │        └ <Thread(ThreadPoolExecutor-35_2, started daemon 7560)>
    │    └ <function _worker at 0x000001B76996ADC0>
    └ <Thread(ThreadPoolExecutor-35_2, started daemon 7560)>

  File "C:\Users\user\.conda\envs\nfcapp\lib\concurrent\futures\thread.py", line 80, in _worker  
    work_item.run()
    │         └ <function _WorkItem.run at 0x000001B76996AEE0>
    └ <concurrent.futures.thread._WorkItem object at 0x000001B704BCE130>

  File "C:\Users\user\.conda\envs\nfcapp\lib\concurrent\futures\thread.py", line 57, in run      
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x000001B704BCE130>     
             │    │   │    └ [<Programmer id=5 tag=True>, 'http://myurl.com/?query=15']
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x000001B704BCE130>
             │    └ <function Core.onWriteTags.<locals>.individual_programmer_write at 0x000001B7049FF9D0>  
             └ <concurrent.futures.thread._WorkItem object at 0x000001B704BCE130>

> File "C:\Users\user\Documents\NFCApp\src\nfcapp\core\__init__.py", line 469, in individual_programmer_write
    success = programmer.write(data)
              │          │     └ 'http://myurl.com/?query=15'
              │          └ <function Programmer.write at 0x000001B77EDC61F0>
              └ <Programmer id=5 tag=True>

  File "C:\Users\user\Documents\NFCApp\src\nfcapp\core\devices.py", line 322, in write
    self._tag.ndef.records = [UriRecord(data)]
    │    │    │               │         └ 'http://myurl.com/?query=15'
    │    │    │               └ <class 'ndef.uri.UriRecord'>
    │    │    └ <property object at 0x000001B77EBD2450>
    │    └ <nfc.tag.tt2_nxp.NTAG213 object at 0x000001B707EF0970>
    └ <Programmer id=5 tag=True>

  File "C:\Users\user\.conda\envs\nfcapp\lib\site-packages\nfc\tag\__init__.py", line 176, in records
    self.octets = b''.join(message_encoder(value))
    │    │                 │               └ [ndef.uri.UriRecord('http://myurl.com/?query=15')]
    │    │                 └ <function message_encoder at 0x000001B77EB24E50>
    │    └ <property object at 0x000001B77EBD2270>
    └ <nfc.tag.tt2_nxp.NTAG21x.NDEF object at 0x000001B704BBE4F0>

  File "C:\Users\user\.conda\envs\nfcapp\lib\site-packages\nfc\tag\__init__.py", line 203, in octets
    self._write_ndef_data(data)
    │    │                └ bytearray(b'\xd1\x01,U\x03myurl.com/?query=15')
    │    └ <function Type2Tag.NDEF._write_ndef_data at 0x000001B708190F70>
    └ <nfc.tag.tt2_nxp.NTAG21x.NDEF object at 0x000001B704BBE4F0>

  File "C:\Users\user\.conda\envs\nfcapp\lib\site-packages\nfc\tag\tt2.py", line 245, in _write_ndef_data
    tag_memory.synchronize()
    │          └ <function Type2TagMemoryReader.synchronize at 0x000001B77FA19310>
    └ <nfc.tag.tt2.Type2TagMemoryReader object at 0x000001B707EF07F0>

  File "C:\Users\user\.conda\envs\nfcapp\lib\site-packages\nfc\tag\tt2.py", line 680, in synchronize
    self._write_to_tag(stop=len(self))
    │    │                      └ <nfc.tag.tt2.Type2TagMemoryReader object at 0x000001B707EF07F0>
    │    └ <function Type2TagMemoryReader._write_to_tag at 0x000001B77FA19790>
    └ <nfc.tag.tt2.Type2TagMemoryReader object at 0x000001B707EF07F0>

  File "C:\Users\user\.conda\envs\nfcapp\lib\site-packages\nfc\tag\tt2.py", line 674, in _write_to_tag
    self._tag.write(index >> 2, data)
    │    │    │     │           └ bytearray(b'4\x03\x00\xd1')
    │    │    │     └ 20
    │    │    └ <function Type2Tag.write at 0x000001B77FA19940>
    │    └ <nfc.tag.tt2_nxp.NTAG213 object at 0x000001B707EF0970>
    └ <nfc.tag.tt2.Type2TagMemoryReader object at 0x000001B707EF07F0>

  File "C:\Users\user\.conda\envs\nfcapp\lib\site-packages\nfc\tag\tt2.py", line 522, in write   
    raise Type2TagCommandError(INVALID_PAGE_ERROR)
          │                    └ 2
          └ <class 'nfc.tag.tt2.Type2TagCommandError'>

nfc.tag.tt2.Type2TagCommandError: invalid page number
```

Please note that "invalid page number" is being sent to ``Type2TagCommandError``, not an errno id.
