### ISSUE TITLE
nfc.tag.tt3.Type3TagCommandError: invalid service code number or attribute

### ISSUE THREAD

**Issue by nanbuwks** [nfcpy/nfcpy#213]
I am trying to read student cards using a RaspberryPi and a PN532.
I've written a program, but it won't work without a dump command in the middle. If I don't put the dump command I get the following error, if I put the dump command it works fine. Oddly enough, if I set servc = 0x090F, it works without the dump command.
Why is this?

Environment:
- PN532 NFC RFID module
- Raspberry Pi Model B+ V1.2
- Raspberry Pi OS Lite armhf-2020-12-04
- Python 3.7.3
- 1.0.4 version of nfcpy

aizu2.py:
```

import nfc
servc = 0x1A8B
def connected(tag):
    service_code = [nfc.tag.tt3.ServiceCode(servc >> 6, servc & 0x3f)]

#    tag.dump()  # why need? 

    bc_id = [nfc.tag.tt3.BlockCode(i) for i in range(3)]
    print (tag.read_without_encryption(service_code, bc_id)) 
    return False
clf = nfc.ContactlessFrontend('tty:AMA0')
try:
  clf.connect(rdwr={'on-connect': connected})
finally:
  clf.close()

```

error without tag.dump()

```
$ python3 aizu2.py
Traceback (most recent call last):
  File "aizu2.py", line 13, in <module>
    clf.connect(rdwr={'on-connect': connected})
  File "/usr/local/lib/python3.7/dist-packages/nfc/clf/__init__.py", line 581, in connect
    result = self._rdwr_connect(rdwr_options, terminate)
  File "/usr/local/lib/python3.7/dist-packages/nfc/clf/__init__.py", line 612, in _rdwr_connect
    if options['on-connect'](tag):
  File "aizu2.py", line 9, in connected
    print (tag.read_without_encryption(service_code, bc_id)) 
  File "/usr/local/lib/python3.7/dist-packages/nfc/tag/tt3.py", line 570, in read_without_encryption
    data = self.send_cmd_recv_rsp(0x06, data, timeout)
  File "/usr/local/lib/python3.7/dist-packages/nfc/tag/tt3.py", line 737, in send_cmd_recv_rsp
    raise Type3TagCommandError(unpack(">H", rsp[10:12])[0])
nfc.tag.tt3.Type3TagCommandError: invalid service code number or attribute
 ```

**Comment by nanbuwks** [comment]
I had the same symptoms on PC Ubuntu 20.04 and SONY RC-S380.
