### ISSUE TITLE
Partial write makes `tag.ndef` on tag disappear

### ISSUE THREAD

**Issue by Spiritdude** [nfcpy/nfcpy#229]
I have been **testing partial write** by moving tag on the writer (PN532 module with serial USB bridge) and moved it away while writing causing this:
```
nfctool:    writing tag: [ndef.text.TextRecord('hello world', 'en', 'UTF-8')]
Traceback (most recent call last):
  File "/home/spirit/Projects/RFID/./nfctool", line 205, in <module>
    sense_tag(clf,write_tag)   
  File "/home/spirit/Projects/RFID/./nfctool", line 62, in sense_tag
    cont = callback(tag)
  File "/home/spirit/Projects/RFID/./nfctool", line 183, in write_tag
    tag.ndef.records = rs
  File "/home/spirit/.local/lib/python3.10/site-packages/nfc/tag/__init__.py", line 175, in records
    self.octets = b''.join(message_encoder(value))
  File "/home/spirit/.local/lib/python3.10/site-packages/nfc/tag/__init__.py", line 202, in octets
    self._write_ndef_data(data)
  File "/home/spirit/.local/lib/python3.10/site-packages/nfc/tag/tt2.py", line 245, in _write_ndef_data
    tag_memory.synchronize()   
  File "/home/spirit/.local/lib/python3.10/site-packages/nfc/tag/tt2.py", line 680, in synchronize
    self._write_to_tag(stop=len(self))
  File "/home/spirit/.local/lib/python3.10/site-packages/nfc/tag/tt2.py", line 674, in _write_to_tag
    self._tag.write(index >> 2, data)
  File "/home/spirit/.local/lib/python3.10/site-packages/nfc/tag/tt2.py", line 514, in write
    rsp = self.transceive(bytearray([0xA2, page % 256]) + data)
  File "/home/spirit/.local/lib/python3.10/site-packages/nfc/tag/tt2.py", line 600, in transceive
    raise Type2TagCommandError(nfc.tag.TIMEOUT_ERROR)
nfc.tag.tt2.Type2TagCommandError: unrecoverable timeout error
```

Now, after this, the tag no longer reports `tag.ndef`, even when I try to `tag.format()`, the `tag.ndef` no longer is reported. I no longer can write to the tag with `tag.ndef.records = [ ... ]` therefore.

```
   while True:
      target = clf.sense(nfc.clf.RemoteTarget('106A'), nfc.clf.RemoteTarget('106B'), nfc.clf.RemoteTarget('212F'))
        
      if target is None:
         time.sleep(0.1)
         continue

      tag = nfc.tag.activate(clf,target)
      ....
```

`tag.dump()` of the NFC tag in question:
```
['000: 53 69 2b 99 (UID0-UID2, BCC0)', '001: c9 60 00 01 (UID3-UID6)', '002: a8 48 00 00 (BCC1, INT, LOCK0-LOCK1)', '003: e1 10 12 00 (OTP0-OTP3)', '004: 01 03 a0 0c |....|', '005: ff 7f ff ff |....|', '006: 01 0e 54 02 |..T.|', '007: 65 6e 68 65 |enhe|', '008: 6c 6c 6f 20 |llo |', '009: 77 6f 72 6c |worl|', '00A: 64 fe 3a 20 |d.: |', '00B: 5b 22 48 65 |["He|', '00C: 6c 6c 6f 22 |llo"|', '00D: 2c 20 22 57 |, "W|', '00E: 6f 72 6c 64 |orld|', '00F: 22 5d 7d fe |"]}.|', '010: 00 00 00 00 |....|', '  *  00 00 00 00 |....|', '027: 00 00 00 00 |....|', '028: 00 00 00 bd |....|', '029: 04 00 00 ff |....|', '02A: 00 05 00 00 |....|', '02B: 00 00 00 00 |....|', '02C: 00 00 00 00 |....|']
```

- Is this a known behavior? 
- Do I "break" a writable  RFID tag by removing it while writing to it?
- How I can recover NDEF writing capability?

Setup:
- PN532 Module with Serial - USB bridge
- NXP NTag213 10x20mm

**Comment by Spiritdude** [comment]
Here the `nf.tag` logger output when accessing `tag` and `tag.dump()`:
```
DEBUG:nfc.tag:trying to activate 106A sdd_res=53692BC9600001 sel_res=00 sens_res=4400
DEBUG:nfc.tag:trying type 2 tag activation for 106A
nfctool: 0: Type2Tag ID=53692BC9600001
DEBUG:nfc.tag.tt2:read pages 0 to 3
DEBUG:nfc.tag.tt2:>> 3000 (0.005000s)
DEBUG:nfc.tag.tt2:<< 53692b99c9600001a8480000e1101200 (0.022513s)
DEBUG:nfc.tag.tt2:read pages 1 to 4
DEBUG:nfc.tag.tt2:>> 3001 (0.005000s)
DEBUG:nfc.tag.tt2:<< c9600001a8480000e11012000103a00c (0.023124s)
DEBUG:nfc.tag.tt2:read pages 2 to 5
DEBUG:nfc.tag.tt2:>> 3002 (0.005000s)
DEBUG:nfc.tag.tt2:<< a8480000e11012000103a00cff7fffff (0.022135s)
DEBUG:nfc.tag.tt2:read pages 3 to 6
DEBUG:nfc.tag.tt2:>> 3003 (0.005000s)
DEBUG:nfc.tag.tt2:<< e11012000103a00cff7fffff010e5402 (0.022031s)
DEBUG:nfc.tag.tt2:read pages 4 to 7
DEBUG:nfc.tag.tt2:>> 3004 (0.005000s)
DEBUG:nfc.tag.tt2:<< 0103a00cff7fffff010e5402656e6865 (0.022166s)
DEBUG:nfc.tag.tt2:read pages 5 to 8
DEBUG:nfc.tag.tt2:>> 3005 (0.005000s)
DEBUG:nfc.tag.tt2:<< ff7fffff010e5402656e68656c6c6f20 (0.022147s)
DEBUG:nfc.tag.tt2:read pages 6 to 9
DEBUG:nfc.tag.tt2:>> 3006 (0.005000s)
DEBUG:nfc.tag.tt2:<< 010e5402656e68656c6c6f20776f726c (0.022599s)
DEBUG:nfc.tag.tt2:read pages 7 to 10
DEBUG:nfc.tag.tt2:>> 3007 (0.005000s)
DEBUG:nfc.tag.tt2:<< 656e68656c6c6f20776f726c64fe3a20 (0.022135s)
DEBUG:nfc.tag.tt2:read pages 8 to 11
DEBUG:nfc.tag.tt2:>> 3008 (0.005000s)
DEBUG:nfc.tag.tt2:<< 6c6c6f20776f726c64fe3a205b224865 (0.022189s)
DEBUG:nfc.tag.tt2:read pages 9 to 12
DEBUG:nfc.tag.tt2:>> 3009 (0.005000s)
DEBUG:nfc.tag.tt2:<< 776f726c64fe3a205b2248656c6c6f22 (0.022110s)
DEBUG:nfc.tag.tt2:read pages 10 to 13
DEBUG:nfc.tag.tt2:>> 300a (0.005000s)
DEBUG:nfc.tag.tt2:<< 64fe3a205b2248656c6c6f222c202257 (0.022602s)
DEBUG:nfc.tag.tt2:read pages 11 to 14
DEBUG:nfc.tag.tt2:>> 300b (0.005000s)
DEBUG:nfc.tag.tt2:<< 5b2248656c6c6f222c2022576f726c64 (0.021865s)
DEBUG:nfc.tag.tt2:read pages 12 to 15
DEBUG:nfc.tag.tt2:>> 300c (0.005000s)
DEBUG:nfc.tag.tt2:<< 6c6c6f222c2022576f726c64225d7dfe (0.022068s)
DEBUG:nfc.tag.tt2:read pages 13 to 16
DEBUG:nfc.tag.tt2:>> 300d (0.005000s)
DEBUG:nfc.tag.tt2:<< 2c2022576f726c64225d7dfe00000000 (0.022051s)
DEBUG:nfc.tag.tt2:read pages 14 to 17
DEBUG:nfc.tag.tt2:>> 300e (0.005000s)
DEBUG:nfc.tag.tt2:<< 6f726c64225d7dfe0000000000000000 (0.021933s)
DEBUG:nfc.tag.tt2:read pages 15 to 18
DEBUG:nfc.tag.tt2:>> 300f (0.005000s)
DEBUG:nfc.tag.tt2:<< 225d7dfe000000000000000000000000 (0.022044s)
DEBUG:nfc.tag.tt2:read pages 16 to 19
DEBUG:nfc.tag.tt2:>> 3010 (0.005000s)
DEBUG:nfc.tag.tt2:<< 00000000000000000000000000000000 (0.022008s)
DEBUG:nfc.tag.tt2:read pages 17 to 20
DEBUG:nfc.tag.tt2:>> 3011 (0.005000s)
DEBUG:nfc.tag.tt2:<< 00000000000000000000000000000000 (0.022583s)
DEBUG:nfc.tag.tt2:read pages 18 to 21
DEBUG:nfc.tag.tt2:>> 3012 (0.005000s)
DEBUG:nfc.tag.tt2:<< 00000000000000000000000000000000 (0.021904s)
DEBUG:nfc.tag.tt2:read pages 19 to 22
DEBUG:nfc.tag.tt2:>> 3013 (0.005000s)
DEBUG:nfc.tag.tt2:<< 00000000000000000000000000000000 (0.021901s)
DEBUG:nfc.tag.tt2:read pages 20 to 23
DEBUG:nfc.tag.tt2:>> 3014 (0.005000s)
DEBUG:nfc.tag.tt2:<< 00000000000000000000000000000000 (0.021988s)
DEBUG:nfc.tag.tt2:read pages 21 to 24
DEBUG:nfc.tag.tt2:>> 3015 (0.005000s)
DEBUG:nfc.tag.tt2:<< 00000000000000000000000000000000 (0.021845s)
DEBUG:nfc.tag.tt2:read pages 22 to 25
DEBUG:nfc.tag.tt2:>> 3016 (0.005000s)
DEBUG:nfc.tag.tt2:<< 00000000000000000000000000000000 (0.021566s)
DEBUG:nfc.tag.tt2:read pages 23 to 26
DEBUG:nfc.tag.tt2:>> 3017 (0.005000s)
DEBUG:nfc.tag.tt2:<< 00000000000000000000000000000000 (0.021569s)
DEBUG:nfc.tag.tt2:read pages 24 to 27
DEBUG:nfc.tag.tt2:>> 3018 (0.005000s)
DEBUG:nfc.tag.tt2:<< 00000000000000000000000000000000 (0.021531s)
DEBUG:nfc.tag.tt2:read pages 25 to 28
DEBUG:nfc.tag.tt2:>> 3019 (0.005000s)
DEBUG:nfc.tag.tt2:<< 00000000000000000000000000000000 (0.021529s)
DEBUG:nfc.tag.tt2:read pages 26 to 29
DEBUG:nfc.tag.tt2:>> 301a (0.005000s)
DEBUG:nfc.tag.tt2:<< 00000000000000000000000000000000 (0.021526s)
DEBUG:nfc.tag.tt2:read pages 27 to 30
DEBUG:nfc.tag.tt2:>> 301b (0.005000s)
DEBUG:nfc.tag.tt2:<< 00000000000000000000000000000000 (0.021598s)
DEBUG:nfc.tag.tt2:read pages 28 to 31
DEBUG:nfc.tag.tt2:>> 301c (0.005000s)
DEBUG:nfc.tag.tt2:<< 00000000000000000000000000000000 (0.021764s)
DEBUG:nfc.tag.tt2:read pages 29 to 32
DEBUG:nfc.tag.tt2:>> 301d (0.005000s)
DEBUG:nfc.tag.tt2:<< 00000000000000000000000000000000 (0.021670s)
DEBUG:nfc.tag.tt2:read pages 30 to 33
DEBUG:nfc.tag.tt2:>> 301e (0.005000s)
DEBUG:nfc.tag.tt2:<< 00000000000000000000000000000000 (0.021765s)
DEBUG:nfc.tag.tt2:read pages 31 to 34
DEBUG:nfc.tag.tt2:>> 301f (0.005000s)
DEBUG:nfc.tag.tt2:<< 00000000000000000000000000000000 (0.021641s)
DEBUG:nfc.tag.tt2:read pages 32 to 35
DEBUG:nfc.tag.tt2:>> 3020 (0.005000s)
DEBUG:nfc.tag.tt2:<< 00000000000000000000000000000000 (0.021704s)
DEBUG:nfc.tag.tt2:read pages 33 to 36
DEBUG:nfc.tag.tt2:>> 3021 (0.005000s)
DEBUG:nfc.tag.tt2:<< 00000000000000000000000000000000 (0.021827s)
DEBUG:nfc.tag.tt2:read pages 34 to 37
DEBUG:nfc.tag.tt2:>> 3022 (0.005000s)
DEBUG:nfc.tag.tt2:<< 00000000000000000000000000000000 (0.021702s)
DEBUG:nfc.tag.tt2:read pages 35 to 38
DEBUG:nfc.tag.tt2:>> 3023 (0.005000s)
DEBUG:nfc.tag.tt2:<< 00000000000000000000000000000000 (0.021616s)
DEBUG:nfc.tag.tt2:read pages 36 to 39
DEBUG:nfc.tag.tt2:>> 3024 (0.005000s)
DEBUG:nfc.tag.tt2:<< 00000000000000000000000000000000 (0.021559s)
DEBUG:nfc.tag.tt2:read pages 37 to 40
DEBUG:nfc.tag.tt2:>> 3025 (0.005000s)
DEBUG:nfc.tag.tt2:<< 000000000000000000000000000000bd (0.021599s)
DEBUG:nfc.tag.tt2:read pages 38 to 41
DEBUG:nfc.tag.tt2:>> 3026 (0.005000s)
DEBUG:nfc.tag.tt2:<< 0000000000000000000000bd040000ff (0.021677s)
DEBUG:nfc.tag.tt2:read pages 39 to 42
DEBUG:nfc.tag.tt2:>> 3027 (0.005000s)
DEBUG:nfc.tag.tt2:<< 00000000000000bd040000ff00050000 (0.021609s)
DEBUG:nfc.tag.tt2:read pages 40 to 43
DEBUG:nfc.tag.tt2:>> 3028 (0.005000s)
DEBUG:nfc.tag.tt2:<< 000000bd040000ff0005000000000000 (0.021592s)
DEBUG:nfc.tag.tt2:read pages 41 to 44
DEBUG:nfc.tag.tt2:>> 3029 (0.005000s)
DEBUG:nfc.tag.tt2:<< 040000ff000500000000000000000000 (0.021521s)
DEBUG:nfc.tag.tt2:read pages 42 to 45
DEBUG:nfc.tag.tt2:>> 302a (0.005000s)
DEBUG:nfc.tag.tt2:<< 00050000000000000000000053692b99 (0.021863s)
DEBUG:nfc.tag.tt2:read pages 43 to 46
DEBUG:nfc.tag.tt2:>> 302b (0.005000s)
DEBUG:nfc.tag.tt2:<< 000000000000000053692b99c9600001 (0.021723s)
DEBUG:nfc.tag.tt2:read pages 44 to 47
DEBUG:nfc.tag.tt2:>> 302c (0.005000s)
DEBUG:nfc.tag.tt2:<< 0000000053692b99c9600001a8480000 (0.021576s)
DEBUG:nfc.tag.tt2:read pages 45 to 48
DEBUG:nfc.tag.tt2:>> 302d (0.005000s)
DEBUG:nfc.tag.tt2:<< 00 (0.018842s)
DEBUG:nfc.tag.tt2:received nak response
```
and the dump() output itself (again as reference):
```
['000: 53 69 2b 99 (UID0-UID2, BCC0)', '001: c9 60 00 01 (UID3-UID6)', '002: a8 48 00 00 (BCC1, INT, LOCK0-LOCK1)', '003: e1 10 12 00 (OTP0-OTP3)', '004: 01 03 a0 0c |....|', '005: ff 7f ff ff |....|', '006: 01 0e 54 02 |..T.|', '007: 65 6e 68 65 |enhe|', '008: 6c 6c 6f 20 |llo |', '009: 77 6f 72 6c |worl|', '00A: 64 fe 3a 20 |d.: |', '00B: 5b 22 48 65 |["He|', '00C: 6c 6c 6f 22 |llo"|', '00D: 2c 20 22 57 |, "W|', '00E: 6f 72 6c 64 |orld|', '00F: 22 5d 7d fe |"]}.|', '010: 00 00 00 00 |....|', '  *  00 00 00 00 |....|', '027: 00 00 00 00 |....|', '028: 00 00 00 bd |....|', '029: 04 00 00 ff |....|', '02A: 00 05 00 00 |....|', '02B: 00 00 00 00 |....|', '02C: 00 00 00 00 |....|']
```

I also tried `tag.format(wipe=True)` but didn't make a difference, the `tag.ndef` remains None.

Btw, looking up `tag.ndef` of the broken NFC tag takes about 320ms, whereas a fully functional NFC tag of the same making takes 66ms.
