### ISSUE TITLE
TypeError: must be string or buffer, not None

### ISSUE THREAD

**Issue by nehpetsde** [nfcpy/nfcpy#23]
I'm occasionally seeing this error on my R-Pi... How do I prevent/fix it?

Traceback (most recent call last):
  File "mainNfc.py", line 286, in <module>
    if (myNfcTag.ndef is None) or (wifiSettings is None):
  File "/home/pi/nfcpy/nfc/tag/__init__.py", line 221, in ndef
    if ndef.has_changed:
  File "/home/pi/nfcpy/nfc/tag/__init__.py", line 135, in has_changed
    old_data, self._data = self._data, self._read_ndef_data()
  File "/home/pi/nfcpy/nfc/tag/tt2.py", line 145, in _read_ndef_data
    if not self._read_capability_data(tag_memory):
  File "/home/pi/nfcpy/nfc/tag/tt2.py", line 128, in _read_capability_data
    if tag_memory[12] != 0xE1:
  File "/home/pi/nfcpy/nfc/tag/tt2.py", line 599, in __getitem__
    self._read_from_tag(stop=key+1)
  File "/home/pi/nfcpy/nfc/tag/tt2.py", line 620, in _read_from_tag
    self._data_from_tag[i:i+16] = self._tag.read(i>>2)
  File "/home/pi/nfcpy/nfc/tag/tt2.py", line 456, in read
    data = self.transceive("\x30"+chr(page%256), timeout=0.005)
  File "/home/pi/nfcpy/nfc/tag/tt2.py", line 565, in transceive
    log.debug("<< {0} ({1:f}s)".format(hexlify(data), elapsed))
TypeError: must be string or buffer, not None

Thanks,

-Juan

**Comment by nehpetsde** [comment]
(by stephen-tiedemann)
This needs more context:
- what version of nfcpy? trunk or release, revision number
- is this first read after discovery?
- are you able to reproduce the error?
- can you enable debug log

**Comment by nehpetsde** [comment]
(by juancarlos-trujillo)
1) I'm using version 0.10.2. 
2) It definitely occurred during a read. Can't tell if it was the very first one after discovery... will double check and let you know...
3) No I haven't been able to reproduce it. So far I have seen it twice.
4) How do I enable debugging?

**Comment by nehpetsde** [comment]
(by juancarlos-trujillo)
Just to confirm that yes, it was the very first read after discovery. From the logs I see that from discovery to the 1st read we waited around 6 minutes.

This is the full log:
INFO:Nfc:+++++++++++++++++++++++++Launched mainNfc at Tue Mar  1 19:09:11 2016
INFO:nfc.clf:searching for reader on path tty:AMA0:pn532
INFO:nfc.clf:using PN532v1.6 at /dev/ttyAMA0
INFO:Nfc:Clf is:   on /dev/ttyAMA0
INFO:Nfc:Starting main loop...
INFO:Nfc:Waiting for new user...
INFO:Nfc:Waiting for new user...
INFO:Nfc:Type2Tag 'NXP NTAG203' ID=04B8C1DA683480
INFO:Nfc:WiFi settings NOT found...
ERROR:nfc.clf:no target for data exchange
Traceback (most recent call last):
  File "mainNfc.py", line 286, in <module>
    if (myNfcTag.ndef is None) or (wifiSettings is None):
  File "/home/pi/nfcpy/nfc/tag/__init__.py", line 221, in ndef
    if ndef.has_changed:
  File "/home/pi/nfcpy/nfc/tag/__init__.py", line 135, in has_changed
    old_data, self._data = self._data, self._read_ndef_data()
  File "/home/pi/nfcpy/nfc/tag/tt2.py", line 145, in _read_ndef_data
    if not self._read_capability_data(tag_memory):
  File "/home/pi/nfcpy/nfc/tag/tt2.py", line 128, in _read_capability_data
    if tag_memory[12] != 0xE1:
  File "/home/pi/nfcpy/nfc/tag/tt2.py", line 599, in __getitem__
    self._read_from_tag(stop=key+1)
  File "/home/pi/nfcpy/nfc/tag/tt2.py", line 620, in _read_from_tag
    self._data_from_tag[i:i+16] = self._tag.read(i>>2)
  File "/home/pi/nfcpy/nfc/tag/tt2.py", line 456, in read
    data = self.transceive("\x30"+chr(page%256), timeout=0.005)
  File "/home/pi/nfcpy/nfc/tag/tt2.py", line 565, in transceive
    log.debug("<< {0} ({1:f}s)".format(hexlify(data), elapsed))
TypeError: must be string or buffer, not None

**Comment by nehpetsde** [comment]
(by stephen-tiedemann)
I could finally reproduce this with "tagtool.py -v" (full memory print) and rapid removal of the tag while it's being read out. The fundamental problem is of course that the tag is no longer in communication range, the difference in nfcpy behaviour will be that a TagCommandError(TIMOUT_ERROR) exception is than raised.

Note that I was only able to verify with full memory print done by tag.dump() and that it only could happen for the tag header data reads because there's a loop that doesn't break on error (in the first place a read() call returned RECEIVE_ERROR and that is ignored).  Code that stops on tag communication errors (like the NDEF read logic in nfcpy) shouldn't have this problem. You may want to check why it happened in your case after the "WiFi settings NOT found...".

I've pushed the changed implementation to trunk (revision 280) and it will be part of the coming release 0.11.0.

**Comment by nehpetsde** [comment]
(by juancarlos-trujillo)
Stephen,

Thanks a lot for taking the time to reproduce the problem!!!

What we do on our code, after a NFC tag has been successfully detected, is to check first if there is any WiFi record on it. If there is a WiFi record, we update our WiFi settings. If it is not, then we print the "WiFi settings NOT found..." message, and then we try to match the NFC Tag ID with the ones we have in our internal database. If we found a match, we authorize the "user" to keep going...

So, do you think we need to modify our code to check for any communication errors before trying to access the NFC tag content? I believe we have some, but I'll double check.

Thanks,

-Juan

**Comment by nehpetsde** [comment]
(by stephen-tiedemann)
Juan,

it's difficult to tell but I'd guess that somewhere you have a separate thread that works with the tag. The traceback above starts at line 286 of mainNfc.py with checking tag.ndef or wifiSettings but wifiSettings is a variable and must be set from somewhere else. If this "somewhere else" piece of code had attempted to read but failed, or had for whatever reason issued a new clf.connect (or clf.sense) call, then this may have caused the subsequent error.

For a bit of background, the ContactlessFrontend implementation memorizes the current target found in the *latest* clf.sense (internally used by clf.connect) call. Any further call to clf.sense replaces that target with a new result - None if no target responds. A Type2Tag may sometimes return a NAK response (negative acknowledge) and then need to be re-sensed. If the Type2Tag would now be gone, the tag object's next attempt to read data fails with the TypeError you've seen. This is now corrected to correctly raise TagCommandError(TIMOUT_ERROR). For code that just works with the NDEF data it should all be handled well - there either is or is not an NdefMessage in the tag.ndef attribute.

/Stephen

**Comment by nehpetsde** [comment]
(by stephen-tiedemann)
Released with version 0.11.0
