### ISSUE TITLE
having trouble with SCL3711

### ISSUE THREAD

**Issue by nehpetsde** [nfcpy/nfcpy#24]
after your changes this morning I tried to use SCL3711. I am getting following error

Traceback (most recent call last):
  File "tagtool.py", line 266, in <module>
    main()
  File "tagtool.py", line 200, in main
    clf = nfc.ContactlessFrontend()
  File "/home/gsridhara/NFC-dev/nfcpy/nfc/clf.py", line 45, in __init__
    try: self.dev = device()
  File "/home/gsridhara/NFC-dev/nfcpy/nfc/dev/pn53x.py", line 237, in __init__
    self.dev = pn53x.search()
  File "/home/gsridhara/NFC-dev/nfcpy/nfc/dev/pn53x.py", line 60, in search
    try: return pn53x_usb(dev)
  File "/home/gsridhara/NFC-dev/nfcpy/nfc/dev/pn53x.py", line 138, in __init__
    self.dh.setConfiguration(dev.configurations[0])
  File "/usr/local/lib/python2.7/dist-packages/usb/legacy.py", line 252, in setConfiguration
    self.dev.set_configuration(configuration)
  File "/usr/local/lib/python2.7/dist-packages/usb/core.py", line 530, in set_configuration
    self._ctx.managed_set_configuration(self, configuration)
  File "/usr/local/lib/python2.7/dist-packages/usb/core.py", line 92, in managed_set_configuration
    self.backend.set_configuration(self.handle, cfg.bConfigurationValue)
AttributeError: 'NoneType' object has no attribute 'bConfigurationValue'
gsridhara@GS-Notebook:~/NFC-dev/nfcpy/examples$ python helloworld.py 
Traceback (most recent call last):
  File "helloworld.py", line 65, in <module>
    main()
  File "helloworld.py", line 32, in main
    clf = nfc.ContactlessFrontend()
  File "/home/gsridhara/NFC-dev/nfcpy/nfc/clf.py", line 45, in __init__
    try: self.dev = device()
  File "/home/gsridhara/NFC-dev/nfcpy/nfc/dev/pn53x.py", line 237, in __init__
    self.dev = pn53x.search()
  File "/home/gsridhara/NFC-dev/nfcpy/nfc/dev/pn53x.py", line 60, in search
    try: return pn53x_usb(dev)
  File "/home/gsridhara/NFC-dev/nfcpy/nfc/dev/pn53x.py", line 138, in __init__
    self.dh.setConfiguration(dev.configurations[0])
  File "/usr/local/lib/python2.7/dist-packages/usb/legacy.py", line 252, in setConfiguration
    self.dev.set_configuration(configuration)
  File "/usr/local/lib/python2.7/dist-packages/usb/core.py", line 530, in set_configuration
    self._ctx.managed_set_configuration(self, configuration)
  File "/usr/local/lib/python2.7/dist-packages/usb/core.py", line 92, in managed_set_configuration
    self.backend.set_configuration(self.handle, cfg.bConfigurationValue)
AttributeError: 'NoneType' object has no attribute 'bConfigurationValue'

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2011-05-25T14:38:07Z
 * owner: gsridhara
 * the launchpad url was https://bugs.launchpad.net/bugs/788157

**Comment by nehpetsde** [comment]
(by gsridhara)
Hello 

Just to add more data to this ,

when I commented the line 
    self.dh.setConfiguration(dev.configurations[0]) 
to check what happens. I go further and 
get

Traceback (most recent call last):
  File "tagtool.py", line 266, in <module>
    main()
  File "tagtool.py", line 203, in main
    tag = poll(clf)
  File "tagtool.py", line 191, in poll
    tag = clf.poll(general_bytes = None)
  File "/home/gsridhara/NFC-dev/nfcpy/nfc/clf.py", line 74, in poll
    data = self.dev.poll_tt3()
  File "/home/gsridhara/NFC-dev/nfcpy/nfc/dev/pn53x.py", line 317, in poll_tt3
    try: rsp = self.dev.in_list_passive_target(1, br, poll_ffff)[0]
  File "/home/gsridhara/NFC-dev/nfcpy/nfc/dev/pn53x.py", line 93, in in_list_passive_target
    raise IOError("in_list_passive_target")
IOError: in_list_passive_target

Eventhough a Tag is present.

Thanks
Gopal

**Comment by nehpetsde** [comment]
(by augustoeae)
I'm having the same problem with SCL3711 on a MacOSX:

ocalhost:examples augustoesteves$ sudo python helloworld.py 
Traceback (most recent call last):
  File "helloworld.py", line 66, in <module>
    main()
  File "helloworld.py", line 34, in main
    clf = nfc.ContactlessFrontend()
  File "/Users/augustoesteves/Dropbox/apps/touchcloud/nfcpy/nfc/clf.py", line 53, in __init__
    self.dev = dev.connect(path)
  File "/Users/augustoesteves/Dropbox/apps/touchcloud/nfcpy/nfc/dev/__init__.py", line 119, in connect
    device = driver.init(dev)
  File "/Users/augustoesteves/Dropbox/apps/touchcloud/nfcpy/nfc/dev/pn53x_usb.py", line 108, in init
    bus = pn53x_usb(usb_dev)
  File "/Users/augustoesteves/Dropbox/apps/touchcloud/nfcpy/nfc/dev/pn53x_usb.py", line 39, in __init__
    self.dh.setConfiguration(dev.configurations[0])
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/usb/legacy.py", line 257, in setConfiguration
    self.dev.set_configuration(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/usb/core.py", line 554, in set_configuration
    self._ctx.managed_set_configuration(self, configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/usb/core.py", line 92, in managed_set_configuration
    self.backend.set_configuration(self.handle, cfg.bConfigurationValue)
AttributeError: 'NoneType' object has no attribute 'bConfigurationValue'

**Comment by nehpetsde** [comment]
(by pefer)
I'm getting the same problem with the helloworld.py demo also with an SCL3711 on OS X 10.8.3. 

When I tried stepping through the managed_set_configuration function in pyusb I found it reaches the "else" case where util.find_descriptor(device, bConfigurationValue=config) then returns None, hence the crash when trying to read back cfg. bConfigurationValue

Traceback (most recent call last):
  File "examples/helloworld.py", line 66, in <module>
    main()
  File "examples/helloworld.py", line 34, in main
    clf = nfc.ContactlessFrontend()
  File "/Volumes/MayBall/Ticketing/nfcpy/nfc/clf.py", line 53, in __init__
    self.dev = dev.connect(path)
  File "/Volumes/MayBall/Ticketing/nfcpy/nfc/dev/__init__.py", line 119, in connect
    device = driver.init(dev)
  File "/Volumes/MayBall/Ticketing/nfcpy/nfc/dev/pn53x_usb.py", line 108, in init
    bus = pn53x_usb(usb_dev)
  File "/Volumes/MayBall/Ticketing/nfcpy/nfc/dev/pn53x_usb.py", line 39, in __init__
    self.dh.setConfiguration(dev.configurations[0])
  File "/Volumes/MayBall/venv/lib/python2.7/site-packages/usb/legacy.py", line 257, in setConfiguration
    self.dev.set_configuration(configuration)
  File "/Volumes/MayBall/venv/lib/python2.7/site-packages/usb/core.py", line 561, in set_configuration
    self._ctx.managed_set_configuration(self, configuration)
  File "/Volumes/MayBall/venv/lib/python2.7/site-packages/usb/core.py", line 99, in managed_set_configuration
    self.backend.set_configuration(self.handle, cfg.bConfigurationValue)
AttributeError: 'NoneType' object has no attribute 'bConfigurationValue'

Any help would be great!

**Comment by nehpetsde** [comment]
(by stephen-tiedemann)
You seem to use pyusb 1.x. The nfcpy trunk version is tested with pyusb 0.4 which is the default on Ubuntu. A modified version that is supposed to work with pyusb 1.x is available on branch 'dev-pyusb'. Please let me know if that works for you, I plan to integrate it for the next major update.
