### ISSUE TITLE
ACS ACR122U on Windows

### ISSUE THREAD

**Issue by nehpetsde** [nfcpy/nfcpy#27]
I followed the instructions for installing the necessary libs on Windows, and on the first page of the tutorial I get the error below.

I'm in a bit of a bind to get this working by the end of the month...  would appreciate any help or advice.  Is there another straightforward means to read the device?  I looked in the ACS SDK but don't understand it.  Seems very concerned with registers and bits on the wire.  I just need to display a message when a card is swiped.

    >>> import nfc
    >>> cls =  nfc.ContactlessFrontend()
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "C:\Programs\Python26\lib\site-packages\nfc\clf.py", line 42, in __init__
        self.dev = dev.connect(path)
      File "C:\Programs\Python26\lib\site-packages\nfc\dev\__init__.py", line 102, in connect
        return driver.init(dev)
      File "C:\Programs\Python26\lib\site-packages\nfc\dev\acr122_usb.py", line 107, in init
        bus = acr122_usb(usb_dev)
      File "C:\Programs\Python26\lib\site-packages\nfc\dev\acr122_usb.py", line 71, in __init__
        self.dh.claimInterface(interface[0])
        
    usb.USBError: libusb0-dll:err [claim_interface] could not claim interface 0, win
     error: The device does not recognize the command.

**Comment by nehpetsde** [comment]
(by stephen-tiedemann)
Mike,

development of nfcpy happens on Ubuntu Linux and hence most testing is there. What I would recommend you is to install Ubuntu in a virtual machineACR122U-A2 with USB forward (I know that VirtualBox does that) and see if your ACS reader works on that platform (note that on Linux you will need to use "sudo python examples/....). That should get some better idea of where the problem might be,

/Stephen

**Comment by nehpetsde** [comment]
(by stephen-tiedemann)
As a further note, ACS122 is probably the worst choice reader for nfcpy (and libnfc, btw). Best is probably the Sony RC-S360 (and 330) but those are difficult to get in many regions. Easier to get and still good is SCM's SCL3711. If you have a chance to switch, do it.

**Comment by nehpetsde** [comment]
(by mike123)
Hi, thanks for the reply.

Unfortunately, I work for a company that has a Windows "multimedia" application.  The boss handed me this reader from a client and said we should have an integration demo ready by the end of the month.  There is no way I'll be able to switch the OS and very slight chance of changing the reader or the demo ceases to make sense quickly.

The "hilarious" part is I'm sitting at Ubuntu now typing this and trying to get the reader to work in Windows via VirtualBox.

**Comment by nehpetsde** [comment]
(by stephen-tiedemann)
Mike, I didn't want to suggest switching OS for the deployment, but just to see if the reader works on Linux. ACS model naming isn't particularly precise and your flavor of ACR122 may actually be different from mine (which is ACR122U203).

**Comment by nehpetsde** [comment]
(by mike123)
Gotcha, I tried it but didn't get very far either:

~/tmp/nfcpy> lsusb
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 002 Device 002: ID 80ee:0021 VirtualBox USB Tablet
Bus 002 Device 004: ID 072f:2200 Advanced Card Systems, Ltd 

~/tmp/nfcpy> sudo python
Python 2.7.2+ (default, Oct  4 2011, 20:06:09) [GCC 4.6.1] on linux2

>>> import nfc
>>> cls = nfc.ContactlessFrontend()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "nfc/clf.py", line 42, in __init__
    self.dev = dev.connect(path)
  File "nfc/dev/__init__.py", line 102, in connect
    return driver.init(dev)
  File "nfc/dev/acr122_usb.py", line 108, in init
    dev = acr122(bus)
  File "nfc/dev/pn53x.py", line 113, in __init__
    ic, ver, rev, support = self.get_firmware_version()
  File "nfc/dev/pn53x.py", line 186, in get_firmware_version
    rsp = self.command(0x02)
  File "nfc/dev/acr122_usb.py", line 49, in command
    raise pn53x.NoResponse("no response from pn53x")
nfc.dev.pn53x.NoResponse: no response from pn53x

I notice the light didnt't go on, so I looked for a driver at the acs site: 
    http://www.acr122.com/acr122-drivers.php
the deb didn't work I guess because I'm on x64.  So I downloaded the source and after two hours finally got it to compile and install.

~/tmp/nfcpy> sudo python
Python 2.7.2+ (default, Oct  4 2011, 20:06:09) [GCC 4.6.1] on linux2
>>> import nfc
>>> cls =  nfc.ContactlessFrontend()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "nfc/clf.py", line 42, in __init__
    self.dev = dev.connect(path)
  File "nfc/dev/__init__.py", line 102, in connect
    return driver.init(dev)
  File "nfc/dev/acr122_usb.py", line 108, in init
    dev = acr122(bus)
  File "nfc/dev/pn53x.py", line 113, in __init__
    ic, ver, rev, support = self.get_firmware_version()
  File "nfc/dev/pn53x.py", line 186, in get_firmware_version
    rsp = self.command(0x02)
  File "nfc/dev/acr122_usb.py", line 51, in command
    raise pn53x.FrameError("unexpected start of frame")
nfc.dev.pn53x.FrameError: [Errno -1] unexpected start of frame
>>> 

sudo pcscd -f
08576742 dyn_unix.c:37:DYN_LoadLibrary() /usr/lib/pcsc/drivers/ifd-acsccid.bundle/Contents/Linux/libacsccid.so: /usr/lib/pcsc/drivers/ifd-acsccid.bundle/Contents/Linux/libacsccid.so: wrong ELF class: ELFCLASS32
00000028 readerfactory.c:941:RFInitializeReader() RFLoadReader failed: 0x80100014
00000009 readerfactory.c:275:RFAddReader() ACS ACR122U init failed.
00000009 hotplug_libudev.c:377:HPAddDevice() Failed adding USB device: ACS ACR122U

Guess its not going to work on x64.

**Comment by nehpetsde** [comment]
(by mike123)
Got a new 32 bit iso and gave it another shot:

ubuntu@ubuntu:~/tmp$  lsusb
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 002 Device 002: ID 80ee:0021 VirtualBox USB Tablet
Bus 002 Device 006: ID 072f:2200 Advanced Card Systems, Ltd 

Was able to get light to come on with this:

ubuntu@ubuntu:~/tmp$ sudo pcscd -f
00000000 ccid_usb.c:743:ReadUSB() usb_bulk_read(002/006): Resource temporarily
unavailable
00000291 ifdhandler.c:1061:IFDHPowerICC() PowerDown failed

ubuntu@ubuntu:~/tmp$ pcsc_scan 
PC/SC device scanner
V 1.4.17 (c) 2001-2009, Ludovic Rousseau <email address hidden>
Compiled with PC/SC lite version: 1.5.5
Scanning present readers...
Waiting for the first reader...^C

Couldn't find it :/

ubuntu@ubuntu:~/tmp/nfcpy$ sudo python
Python 2.7.2+ (default, Oct  4 2011, 20:03:08) [GCC 4.6.1] on linux2

>>> >>> import nfc
>>> >>> c = nfc.ContactlessFrontend()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "nfc/clf.py", line 42, in __init__
    self.dev = dev.connect(path)
  File "nfc/dev/__init__.py", line 102, in connect
    return driver.init(dev)
  File "nfc/dev/acr122_usb.py", line 108, in init
    dev = acr122(bus)
  File "nfc/dev/pn53x.py", line 113, in __init__
    ic, ver, rev, support = self.get_firmware_version()
  File "nfc/dev/pn53x.py", line 186, in get_firmware_version
    rsp = self.command(0x02)
  File "nfc/dev/acr122_usb.py", line 51, in command
    raise pn53x.FrameError("unexpected start of frame")
nfc.dev.pn53x.FrameError: [Errno -1] unexpected start of frame
>>> >>> 

I think this is where I give up.  Just wasted four hours :(.

**Comment by nehpetsde** [comment]
(by vnwarrior)
@mike - I have nfcpy working perfectly in windows. I think the problem with you is the incorrect installation of libusb and associated drivers.

Here's my suggestion - use a tool called Zadig to install your libusb drivers (I personally use the libK version bundled with Zadig). Remember also to download http://libusbx.org/  and  copy libusbx\MS32\dll\libusb-1.0.dll to c:\windows\sytem32

make sure this is working

from usb import core   
dev = core.find(idVendor=0x072f, idProduct=0x2200)
print dev == None  #should return false

**Comment by nehpetsde** [comment]
(by mike123)
Thanks for your help, although  I'm no longer on that project, it was over two years ago now.

**Comment by nehpetsde** [comment]
(by jkuhn)
Had a similar issue with the Sony RC-S380 on Windows using nfcpy 0.9.2

The following patch to 'nfc/dev/__init__.py' fixed it:

@@ -64,7 +64,11 @@
                     device = driver.init(usb)
                 except IOError:
                     continue
-                device._path = "usb:{0:03}:{1:03}".format(int(bus), int(dev))
+                if sys.platform == 'win32':
+                    device._path = "usb:{0:03}:{1:03}".format(int(bus.split('-')[1]), int(dev.split('-')[1]))
+                else:
+                    device._path = "usb:{0:03}:{1:03}".format(int(bus), int(dev))
+
                 return device
 
     found = transport.TTY.find(path)

**Comment by nehpetsde** [comment]
(by stephen-tiedemann)
Which libusb version are you using? I've checked with a fresh Win7, libusb-win32 (v1.2.6.0) installed through Zadig.exe and pyusb_1.0.0b2 without problems.

**Comment by nehpetsde** [comment]
(by jkuhn)
The same version of libusb-win32, but under Windows 8.1 Pro and with pyusb-0.4.3.

**Comment by nehpetsde** [comment]
(by stephen-tiedemann)
PyUSB is no longer used but switched to python-libusb1, a native wrapper for libusb. On Windows this uses the Microsoft WinUSB.sys driver - so it's all different. Please file an issue at https:/github.com/nfcpy/nfcpy if there still is a problem.
