### ISSUE TITLE
IndexError when restarting LLCP session without removing SCL3711

### ISSUE THREAD

**Issue by nehpetsde** [nfcpy/nfcpy#29]
Developing a SNEP server for communicating with the Galaxy Nexus, I've been getting the following error for a while. It occurs when I close and start a new LLCP connection, without removing the device in the mean time (the reader is an SCM SCL3711). 

searching for a usable reader
searching for a usb bus reader
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/nfc/llcp/llc.py", line 296, in run
    try: data = self.mac.exchange(pdu.to_string(), recv_timeout)
  File "/usr/local/lib/python2.7/dist-packages/nfc/dep.py", line 56, in exchange
    data = self._dev.dep_exchange(data, timeout)
  File "/usr/local/lib/python2.7/dist-packages/nfc/dev/pn53x.py", line 449, in dep_exchange
    status, data_in = self.dev.in_data_exchange(0x01, data, timeout)
  File "/usr/local/lib/python2.7/dist-packages/nfc/dev/pn53x.py", line 241, in in_data_exchange
    rsp = self.command(0x40, chr(tg) + data_out, timeout)
  File "/usr/local/lib/python2.7/dist-packages/nfc/dev/pn53x.py", line 152, in command
    if frame[3] == 255 and frame[4] == 255:
IndexError: bytearray index out of range

I've temporarily fixed it by adding the following check to pn53x.py:152, although I'm not sure of the consequences to the rest of the system:

        if len(frame) < 5:
            raise FrameError("invalid frame length, too short")

At least this frame error is caught.

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2012-03-27T07:48:35Z
 * owner: 09539-8
 * the launchpad url was https://bugs.launchpad.net/bugs/965991

**Comment by nehpetsde** [comment]
(by stephen-tiedemann)
Pelle, the length check does not harm in any way and I may add it to trunk. 

When you say that fixed it, does it mean your code runs on successfully or just that there is then a FrameError raised instead of IndexError and it then breaks?

The log trace looks a bit strange. The exception happens before an LLCP Link is running but is raised in and LLC trhead when using mac_exchange. This does not fit together. Could you clarify how you are closing and starting a new LLCP connection.

**Comment by nehpetsde** [comment]
(by 09539-8)
I have attached the code for the wrapper module I have written for simple communication with a Galaxy Nexus (or in general any Beam device). General procedure is to call BeamSession.open(), BeamSession.receive(), BeamSession.send() and then BeamSession.close(). 

It seems the exception is thrown if the above methods are called in order inside a loop, and the connection is re-opened without the peer device being physically removed. That causes the IndexError to be thrown, probably after the BeamSession.open() call. I don't know why, I'm not sure what difference physically removing the device makes, as it works when running in a loop, if the device is removed and then placed in NFC proximity again. 

After the fix (although possibly unrelated), I'm also getting the following errors:

Traceback (most recent call last):
  File "/usr/lib/python2.6/threading.py", line 532, in __bootstrap_inner
    self.run()
  File "/home/root/Terminal/model/ClientHandler.py", line 72, in run
    self.__session.close()
  File "/home/root/Terminal/client/BeamSession.py", line 102, in close
    self.__clf.close()
  File "/usr/lib/python2.6/site-packages/nfc/clf.py", line 52, in close
    self.dev.close()
  File "/usr/lib/python2.6/site-packages/nfc/dev/pn53x.py", line 330, in close
    try: self.dev.rf_configuration(0x01, "\x00") # RF off
  File "/usr/lib/python2.6/site-packages/nfc/dev/pn53x.py", line 199, in rf_configuration
    return self.command(0x32, bytearray([cfg_item]) + bytearray(cfg_data))
  File "/usr/lib/python2.6/site-packages/nfc/dev/pn53x.py", line 172, in command
    raise FrameError("unexpected response code")
FrameError: [Errno -1] unexpected response code


Traceback (most recent call last):
  File "/usr/lib/python2.6/threading.py", line 532, in __bootstrap_inner
    self.run()
  File "/home/root/Terminal/model/ClientHandler.py", line 72, in run
    self.__session.close()
  File "/home/root/Terminal/client/BeamSession.py", line 102, in close
    self.__clf.close()
  File "/usr/lib/python2.6/site-packages/nfc/clf.py", line 52, in close
    self.dev.close()
  File "/usr/lib/python2.6/site-packages/nfc/dev/pn53x.py", line 330, in close
    try: self.dev.rf_configuration(0x01, "\x00") # RF off
  File "/usr/lib/python2.6/site-packages/nfc/dev/pn53x.py", line 199, in rf_configuration
    return self.command(0x32, bytearray([cfg_item]) + bytearray(cfg_data))
  File "/usr/lib/python2.6/site-packages/nfc/dev/pn53x.py", line 165, in command
    raise FrameError("lenght checksum error")
FrameError: [Errno -1] lenght checksum error

**Comment by nehpetsde** [comment]
(by stephen-tiedemann)
Not sure why this was left open but pretty sure it's fixed since a long time.
