### ISSUE TITLE
newest nfcpy verison not working on Windows XP and virtualized Linux (Virtualbox)

### ISSUE THREAD

**Issue by nehpetsde** [nfcpy/nfcpy#3]
when trying to access the RC-S330 the error "LookupError: couldn't find any usable nfc reader" is reported and the program terminates. The example scripts work when the nfc module is replaced with an older version. I suspect a timing issue.

Details:
Searching USB bus for contactless reader
found device at USB port bus-0:\\.\libusb0-0001--0x054c-0x02e1
Traceback (most recent call last):
  File "trunk\examples\tagtool.py", line 266, in <module>
    main()
  File "trunk\examples\tagtool.py", line 200, in main
    clf = nfc.ContactlessFrontend()
  File "trunk\nfc\clf.py", line 50, in __init__
    raise LookupError("couldn't find any usable nfc reader")
LookupError: couldn't find any usable nfc reader

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2011-03-10T13:12:04Z
 * owner: webreg-fd
 * assignee: webreg-fd
 * the launchpad url was https://bugs.launchpad.net/bugs/732563

**Comment by nehpetsde** [comment]
(by webreg-fd)
Fix:  in pn53x.py, line 59  add the below line
self.dh.setConfiguration(dev.configurations[0]) 

this section should then be:
try:
                            self.dh = dev.open()
                            self.dh.setConfiguration(dev.configurations[0])
                            self.dh.claimInterface(0)
                            conf = dev.configurations[0]
                            intf = conf.interfaces[0]
                            self.ep = intf[0].endpoints[0].address
                            self.usb_out = intf[0].endpoints[0].address
                            self.usb_inp = intf[0].endpoints[1].address
                        except usb.USBError:
                            self.dh = None
                            continue
                        break
