### ISSUE TITLE
USBERROR: Connection timed out

### ISSUE THREAD

**Issue by nehpetsde** [nfcpy/nfcpy#31]
I get this while running helloworld.py

-110
Traceback (most recent call last):
  File "nfcTest.py", line 46, in <module>
    main()
  File "nfcTest.py", line 34, in main
    tag = clf.poll()
  File "/home/islamhassan/Development/python/sooft/loyalityNFC/nfc/clf.py", line 79, in poll
    target = self.dev.poll(protocol_data)
  File "/home/islamhassan/Development/python/sooft/loyalityNFC/nfc/dev/pn53x.py", line 337, in poll
    target = poll()
  File "/home/islamhassan/Development/python/sooft/loyalityNFC/nfc/dev/pn53x.py", line 347, in poll_nfca
    rsp = self.dev.in_list_passive_target("106A", "")
  File "/home/islamhassan/Development/python/sooft/loyalityNFC/nfc/dev/pn53x.py", line 209, in in_list_passive_target
    rsp_data = self.command(0x4A, cmd_data, timeout=1000)
  File "/home/islamhassan/Development/python/sooft/loyalityNFC/nfc/dev/acr122_usb.py", line 45, in command
    self.bus.write(frame)
  File "/home/islamhassan/Development/python/sooft/loyalityNFC/nfc/dev/pn53x_usb.py", line 65, in write
    self.dh.bulkWrite(self.usb_out, frame)
usb.USBError: Connection timed out

The only modifications I did was removing the french and german records.
I'm using ACR122U-AU and ACR122T-E2

**Comment by nehpetsde** [comment]
(by stephen-tiedemann)
Please try again with the newest revision on trunk. There's a couple of changes made and I can only trace things based on that version. Thanks a lot.

**Comment by nehpetsde** [comment]
(by stephen-tiedemann)
There is no new information whether this bug still exists. It was either implicitly fixed by some later update or the devices ACR122U-AU and ACR122T-E2 are not supported (only ACR122U-WB-R and ACR122U-A9 are available for testing).
