### ISSUE TITLE
Reader broken?

### ISSUE THREAD

**Issue by nehpetsde** [nfcpy/nfcpy#36]
I have two NFC readers, see https://i.imgur.com/bzmcAqu.jpg

Both are detected on Ubuntu Utopic as:

Bus 003 Device 0xy: ID 072f:2200 Advanced Card Systems, Ltd

Where device number 0xy increases when pluging in the other device. The one on the left isn't working properly. The green LED is blinking when connected. Looking at /var/log/sys the differences are minimal. See for left reader in image

Dec  9 14:33:06 *** kernel: [  512.430663] usb 3-1: new full-speed USB device number 11 using xhci_hcd
Dec  9 14:33:06 *** kernel: [  512.562084] usb 3-1: New USB device found, idVendor=072f, idProduct=2200
Dec  9 14:33:06 *** kernel: [  512.562095] usb 3-1: New USB device strings: Mfr=1, Product=2, SerialNumber=0
Dec  9 14:33:06 *** kernel: [  512.562101] usb 3-1: Product: CCID USB Reader
Dec  9 14:33:06 *** kernel: [  512.562106] usb 3-1: Manufacturer:
Dec  9 14:33:06 *** mtp-probe: checking bus 3, device 11: "/sys/devices/pci0000:00/0000:00:14.0/usb3/3-1"
Dec  9 14:33:06 *** mtp-probe: bus: 3, device: 11 was not an MTP device

and the right reader:

Dec  9 14:33:46 *** kernel: [  552.023415] usb 3-1: new full-speed USB device number 12 using xhci_hcd
Dec  9 14:33:46 *** kernel: [  552.155217] usb 3-1: New USB device found, idVendor=072f, idProduct=2200
Dec  9 14:33:46 *** kernel: [  552.155227] usb 3-1: New USB device strings: Mfr=1, Product=2, SerialNumber=0
Dec  9 14:33:46 *** kernel: [  552.155233] usb 3-1: Product: ACR122U PICC Interface
Dec  9 14:33:46 *** kernel: [  552.155238] usb 3-1: Manufacturer: ACS
Dec  9 14:33:46 *** kernel: [  552.155798] usb 3-1: ep 0x81 - rounding interval to 256 microframes, ep desc says 400 microframes
Dec  9 14:33:46 *** mtp-probe: checking bus 3, device 12: "/sys/devices/pci0000:00/0000:00:14.0/usb3/3-1"
Dec  9 14:33:46 *** mtp-probe: bus: 3, device: 12 was not an MTP device

One can see that Product and Manufacturer and ep 0x81 (?) differs.

Output of the left reader for tagtool.py show is:

nfcpy-0.9.1$ python examples/tagtool.py show
[nfc.clf] searching for reader with path 'usb'
Traceback (most recent call last):
  File "examples/tagtool.py", line 475, in <module>
    TagTool().run()
  File "/home/***/nfcpy-0.9.1/examples/cli.py", line 283, in run
    while self.run_once() and self.options.loop:
  File "/home/***/nfcpy-0.9.1/examples/cli.py", line 230, in run_once
    try: clf = nfc.ContactlessFrontend(device)
  File "/home/***/nfcpy-0.9.1/nfc/clf.py", line 105, in __init__
    if path and not self.open(path):
  File "/home/***/nfcpy-0.9.1/nfc/clf.py", line 156, in open
    self.dev = nfc.dev.connect(path)
  File "/home/***/nfcpy-0.9.1/nfc/dev/__init__.py", line 64, in connect
    device = driver.init(usb)
  File "/home/***/nfcpy-0.9.1/nfc/dev/acr122.py", line 121, in init
    chipset = Chipset(transport)
  File "/home/***/nfcpy-0.9.1/nfc/dev/acr122.py", line 46, in __init__
    log.error("{0} not supported, need 2.xx".format(frame[10:]))
UnboundLocalError: local variable 'frame' referenced before assignment

and the right reader is:

nfcpy-0.9.1$ python examples/tagtool.py show
[nfc.clf] searching for reader with path 'usb'
[nfc.clf] using ACS ACR122U PICC Interface at usb:003:012
[main] touch a tag
[nfc.dev] Driver.set_communication_mode() should be implemented.
Type2Tag ATQ=0200 SAK=18 UID=***

For this I didn't had to add the udev rules or modprobe blacklist to get it working.

Ubuntu Utopic 14.10 had installed:
  python        2.7.8-1
  libnfc5:amd64 1.7.1-1
  python-usb    0.4.3-1

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2014-12-09T13:48:10Z
 * owner: pander
 * the launchpad url was https://bugs.launchpad.net/bugs/1400706

**Comment by nehpetsde** [comment]
(by stephen-tiedemann)
Despite the identical USB vendor and product id these are two quite different devices. The touchatag reader is a USB CCID profile. I remember that I have tried to get it working some time ago, but gave up. 

The readers supported by nfcpy are listed here: https://nfcpy.readthedocs.org/en/latest/overview.html#supported-hardware.

**Comment by nehpetsde** [comment]
(by stephen-tiedemann)
"touchatag" reader is not supported.
