### ISSUE TITLE
Breaking change from 0.9.2 to 0.10.0

### ISSUE THREAD

**Issue by nehpetsde** [nfcpy/nfcpy#37]
I just downloaded the latest release (0.10.0) and gave it a quick spin. Unfortunately the first tryout already failed:

/nfcpy-0.10.0/examples# python tagtool.py --device tty:AMA0:pn53x show
[nfc.clf] searching for reader on path tty:AMA0:pn53x
Traceback (most recent call last):
  File "tagtool.py", line 569, in <module>
    TagTool().run()
  File "/root/nfcpy-0.10.0/examples/cli.py", line 415, in run
    while self.run_once() and self.options.loop:
  File "/root/nfcpy-0.10.0/examples/cli.py", line 344, in run_once
    clf = nfc.ContactlessFrontend(path)
  File "/root/nfcpy-0.10.0/nfc/clf/__init__.py", line 72, in __init__
    if path and not self.open(path):
  File "/root/nfcpy-0.10.0/nfc/clf/__init__.py", line 146, in open
    self.device = device.connect(path)
  File "/root/nfcpy-0.10.0/nfc/clf/device.py", line 104, in connect
    device = driver.init(tty)
AttributeError: 'module' object has no attribute 'init'

This does not happen with the previous release 0.9.2. Am I missing any new dependencies?

Regards,
Florian

**Comment by nehpetsde** [comment]
(by 7-kontakt)
Ok, just found it myself. The device needs to be specific:
"--device tty:AMA0:pn53x" needs to be "--device tty:AMA0:pn532"

I changed the ticket to invalid.

**Comment by nehpetsde** [comment]
(by stephen-tiedemann)
Version 0.10.1 now issues a warning when pn53x is attempted to be used as a driver.
