### ISSUE TITLE
error on examples\tagtool.py

### ISSUE THREAD

**Issue by userDevop123** [nfcpy/nfcpy#80]
i tried to run examples\tagtool.py on windows 10 64 bit

i get this error

```
C:\Users\X\Downloads\nfcpy-master\nfcpy-master\examples>python tagtool.py
Traceback (most recent call last):
  File "tagtool.py", line 35, in <module>
    from cli import CommandLineInterface
  File "C:\Users\X\Downloads\nfcpy-master\nfcpy-master\examples\cli.py", line 32, in <module>
    import nfc
  File "c:\Python27\lib\site-packages\nfc\__init__.py", line 22, in <module>
    from . import clf                                                  # noqa: F401
  File "c:\Python27\lib\site-packages\nfc\clf\__init__.py", line 25, in <module>
    from . import device
  File "c:\Python27\lib\site-packages\nfc\clf\device.py", line 32, in <module>
    from . import transport
  File "c:\Python27\lib\site-packages\nfc\clf\transport.py", line 31, in <module>
    import usb1 as libusb
  File "c:\Python27\lib\site-packages\usb1\__init__.py", line 61, in <module>
    from . import libusb1
  File "c:\Python27\lib\site-packages\usb1\libusb1.py", line 199, in <module>
    libusb = _loadLibrary()
  File "c:\Python27\lib\site-packages\usb1\libusb1.py", line 173, in _loadLibrary
    return dll_loader('libusb-1.0' + suffix, **loader_kw)
  File "c:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 193] %1 is not a valid Win32 application
```

or when i press python -m nfc  i get

```
C:\Users\X\Downloads\nfcpy-master\nfcpy-master\examples>python -m nfc
Traceback (most recent call last):
  File "c:\Python27\lib\runpy.py", line 163, in _run_module_as_main
    mod_name, _Error)
  File "c:\Python27\lib\runpy.py", line 111, in _get_module_details
    __import__(mod_name)  # Do not catch exceptions initializing package
  File "c:\Python27\lib\site-packages\nfc\__init__.py", line 22, in <module>
    from . import clf                                                  # noqa: F401
  File "c:\Python27\lib\site-packages\nfc\clf\__init__.py", line 25, in <module>
    from . import device
  File "c:\Python27\lib\site-packages\nfc\clf\device.py", line 32, in <module>
    from . import transport
  File "c:\Python27\lib\site-packages\nfc\clf\transport.py", line 31, in <module>
    import usb1 as libusb
  File "c:\Python27\lib\site-packages\usb1\__init__.py", line 61, in <module>
    from . import libusb1
  File "c:\Python27\lib\site-packages\usb1\libusb1.py", line 199, in <module>
    libusb = _loadLibrary()
  File "c:\Python27\lib\site-packages\usb1\libusb1.py", line 173, in _loadLibrary
    return dll_loader('libusb-1.0' + suffix, **loader_kw)
  File "c:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 193] %1 is not a valid Win32 application
```

i have  python 2.7.13

**Comment by nehpetsde** [comment]
Have you installed the libusb library as described in getting started?

**Comment by userDevop123** [comment]
@nehpetsde i actually not sure if i understand the installation instructions
if i understand well if need :
1-install WinUSB with  Zadig
2- copy 2 dll from  libusb i download from  http://libusb.info/ for 2 folder on windows
3- install nfcpy with `$ pip install -U nfcpy`

do i understand well?
about step number 1:
what does it mean ( from  installation instructions)

>  select your device and choose the WinUSB driver to install

do i need to connect the reader and select it there , and then choose WinUSB?
do i need to do it per type of reader?
