### ISSUE TITLE
usb1.USBErrorTimeout: LIBUSB_ERROR_TIMEOUT [-7]

### ISSUE THREAD

**Issue by chelinho139** [nfcpy/nfcpy#90]
Error using version 0.13.4
------

$ python -m nfc

This is the 0.13.4 version of nfcpy run in Python 2.7.10
on Darwin-16.7.0-x86_64-i386-64bit
I'm now searching your system for contactless devices
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Library/Python/2.7/site-packages/nfc/__main__.py", line 204, in <module>
    main(parser.parse_args())
  File "/Library/Python/2.7/site-packages/nfc/__main__.py", line 54, in main
    clf = nfc.ContactlessFrontend(path)
  File "/Library/Python/2.7/site-packages/nfc/clf/__init__.py", line 74, in __init__
    if path and not self.open(path):
  File "/Library/Python/2.7/site-packages/nfc/clf/__init__.py", line 148, in open
    self.device = device.connect(path)
  File "/Library/Python/2.7/site-packages/nfc/clf/device.py", line 89, in connect
    device = driver.init(transport.USB(bus, dev))
  File "/Library/Python/2.7/site-packages/nfc/clf/transport.py", line 229, in __init__
    self.open(usb_bus, dev_adr)
  File "/Library/Python/2.7/site-packages/nfc/clf/transport.py", line 278, in open
    self._manufacturer_name = dev.getManufacturer()
  File "build/bdist.macosx-10.12-intel/egg/usb1/__init__.py", line 2026, in getManufacturer
  File "build/bdist.macosx-10.12-intel/egg/usb1/__init__.py", line 2018, in _getASCIIStringDescriptor
  File "build/bdist.macosx-10.12-intel/egg/usb1/__init__.py", line 1413, in getASCIIStringDescriptor
  File "build/bdist.macosx-10.12-intel/egg/usb1/__init__.py", line 133, in mayRaiseUSBError
  File "build/bdist.macosx-10.12-intel/egg/usb1/__init__.py", line 125, in raiseUSBError
usb1.USBErrorTimeout: LIBUSB_ERROR_TIMEOUT [-7]

any ideas how to solve it?

**Comment by StephenTiedemann** [comment]
Looks like a low level communication problem with your device. Could it be broken or otherwise crap. You could just try in a Python interpreter to import usb1 and do some basic exchanges with the device.
