### ISSUE TITLE
Permission denied when opening nfc.ContactlessFrontend('usb:054c:06c1') as clf

### ISSUE THREAD

**Issue by ghxbob** [nfcpy/nfcpy#91]
when i run the examples for emulating a T3T , I met error  "Permission denied", I have no clue, hope for your help.

I also checked in macOS, the same error happens, I'm sure i run as administrator of the PC or mac.
I use SONY RC-S380.

py file also attached.
[T3T.py.zip](https://github.com/nfcpy/nfcpy/files/1596196/T3T.py.zip)

Traceback (most recent call last):
  File "D:\00 Software\T3T.py", line 37, in <module>
    with nfc.ContactlessFrontend('usb:054c:06c1') as clf:
  File "C:\Python27\lib\site-packages\nfc\clf\__init__.py", line 74, in __init__
    if path and not self.open(path):
  File "C:\Python27\lib\site-packages\nfc\clf\__init__.py", line 148, in open
    self.device = device.connect(path)
  File "C:\Python27\lib\site-packages\nfc\clf\device.py", line 95, in connect
    raise error
IOError: [Errno 13] Permission denied

**Comment by ghxbob** [comment]
Anyone could help？

**Comment by ghxbob** [comment]
After one day study, I find where the problem come from.
I install the "wrong" driver for SONY RC-S380, after i uninstall SONY's driver and install Win-USB with zadig, the problem is sovled.
